/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Return the authenticated caller (control plane)
     * @description Requires a Logto JWT: `Authorization: Bearer <token>` with the `relay:read` scope. Returns 401 without a valid token and 403 without the scope.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              user_id?: string;
              org_id?: null | string;
              scopes?: string[];
              is_platform_admin?: boolean;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/platform/orgs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List organizations */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              data?: {
                object?: string;
                id?: string;
                name?: string;
                /** @enum {string} */
                status?: 'active' | 'suspended';
                /** @enum {string} */
                onboarding_state?: 'created' | 'admin_invited' | 'provider_added' | 'first_request';
                logto_org_id?: string;
                created_at?: string;
              }[];
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    put?: never;
    /** Onboard a new organization (Logto org + entitlements + admin invite) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            name: string;
            adminEmail?: string;
            /** @enum {string} */
            template?: 'default' | 'trial' | 'internal';
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              id?: string;
              name?: string;
              /** @enum {string} */
              status?: 'active' | 'suspended';
              /** @enum {string} */
              onboarding_state?: 'created' | 'admin_invited' | 'provider_added' | 'first_request';
              logto_org_id?: string;
              created_at?: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/platform/orgs/{orgId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve an organization */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              id?: string;
              name?: string;
              /** @enum {string} */
              status?: 'active' | 'suspended';
              /** @enum {string} */
              onboarding_state?: 'created' | 'admin_invited' | 'provider_added' | 'first_request';
              logto_org_id?: string;
              created_at?: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/platform/orgs/{orgId}/suspend': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Suspend an organization (data plane rejects its keys ≤1s later) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              id?: string;
              name?: string;
              /** @enum {string} */
              status?: 'active' | 'suspended';
              /** @enum {string} */
              onboarding_state?: 'created' | 'admin_invited' | 'provider_added' | 'first_request';
              logto_org_id?: string;
              created_at?: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/platform/orgs/{orgId}/unsuspend': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reactivate a suspended organization */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              id?: string;
              name?: string;
              /** @enum {string} */
              status?: 'active' | 'suspended';
              /** @enum {string} */
              onboarding_state?: 'created' | 'admin_invited' | 'provider_added' | 'first_request';
              logto_org_id?: string;
              created_at?: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/platform/orgs/{orgId}/entitlements': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read an organization's entitlement flags */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              org_id?: string;
              features?: {
                [key: string]: unknown;
              };
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    /** Replace/merge an organization's entitlement flags (hot-reloaded ≤1s) */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            features: {
              [key: string]: unknown;
            };
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              org_id?: string;
              features?: {
                [key: string]: unknown;
              };
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/platform/orgs/{orgId}/onboarding/advance': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Advance the onboarding state machine one step */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** @enum {string} */
            state: 'admin_invited' | 'provider_added' | 'first_request';
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              id?: string;
              name?: string;
              /** @enum {string} */
              status?: 'active' | 'suspended';
              /** @enum {string} */
              onboarding_state?: 'created' | 'admin_invited' | 'provider_added' | 'first_request';
              logto_org_id?: string;
              created_at?: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/platform/orgs/{orgId}/members': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List an organization’s members */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              data?: {
                object?: string;
                id?: string;
                name?: null | string;
                email?: null | string;
              }[];
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    put?: never;
    /** Invite a member (by email) into the organization */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            email: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              invitation_id?: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/platform/orgs/{orgId}/members/{userId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove a member from the organization */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
          userId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/apps': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List applications */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              data?: {
                object?: string;
                id?: string;
                name?: string;
                description?: null | string;
                created_at?: string;
              }[];
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    put?: never;
    /** Create an application */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            name: string;
            description?: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              id?: string;
              name?: string;
              description?: null | string;
              created_at?: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/apps/{appId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve an application */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          appId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              id?: string;
              name?: string;
              description?: null | string;
              created_at?: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/apps/{appId}/keys': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List an application’s virtual keys (never returns secrets) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          appId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              data?: {
                object?: string;
                id?: string;
                app_id?: string;
                key_id?: null | string;
                name?: null | string;
                last4?: string;
                /** @enum {string} */
                environment?: 'live' | 'test';
                /** @enum {string} */
                status?: 'active' | 'revoked';
                successor_id?: null | string;
                grace_until?: null | string;
                created_at?: string;
                revoked_at?: null | string;
              }[];
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    put?: never;
    /** Issue a virtual key (plaintext returned once) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          appId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            name?: string;
            /** @enum {string} */
            environment?: 'live' | 'test';
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              id?: string;
              app_id?: string;
              key_id?: null | string;
              name?: null | string;
              last4?: string;
              /** @enum {string} */
              environment?: 'live' | 'test';
              /** @enum {string} */
              status?: 'active' | 'revoked';
              successor_id?: null | string;
              grace_until?: null | string;
              created_at?: string;
              revoked_at?: null | string;
              key?: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/keys/{keyId}/rotate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rotate a key: issue a successor, grace the predecessor */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          keyId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              id?: string;
              app_id?: string;
              key_id?: null | string;
              name?: null | string;
              last4?: string;
              /** @enum {string} */
              environment?: 'live' | 'test';
              /** @enum {string} */
              status?: 'active' | 'revoked';
              successor_id?: null | string;
              grace_until?: null | string;
              created_at?: string;
              revoked_at?: null | string;
              key?: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/keys/{keyId}/revoke': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke a key immediately (data plane rejects it ≤1s later) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          keyId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              id?: string;
              app_id?: string;
              key_id?: null | string;
              name?: null | string;
              last4?: string;
              /** @enum {string} */
              environment?: 'live' | 'test';
              /** @enum {string} */
              status?: 'active' | 'revoked';
              successor_id?: null | string;
              grace_until?: null | string;
              created_at?: string;
              revoked_at?: null | string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/providers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List provider credentials (metadata only) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              data?: {
                object?: string;
                id?: string;
                name?: string;
                /** @enum {string} */
                provider?: 'openai' | 'anthropic' | 'openai_compat';
                last4?: string;
                base_url?: null | string;
                /** @enum {string} */
                status?: 'active' | 'disabled';
                health_score?: number;
                created_at?: string;
              }[];
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    put?: never;
    /** Store a provider credential (sealed on write, never returned) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            name: string;
            /** @enum {string} */
            provider: 'openai' | 'anthropic' | 'openai_compat';
            apiKey: string;
            /** Format: uri */
            baseUrl?: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              id?: string;
              name?: string;
              /** @enum {string} */
              provider?: 'openai' | 'anthropic' | 'openai_compat';
              last4?: string;
              base_url?: null | string;
              /** @enum {string} */
              status?: 'active' | 'disabled';
              health_score?: number;
              created_at?: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/providers/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve a provider credential (metadata only) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              id?: string;
              name?: string;
              /** @enum {string} */
              provider?: 'openai' | 'anthropic' | 'openai_compat';
              last4?: string;
              base_url?: null | string;
              /** @enum {string} */
              status?: 'active' | 'disabled';
              health_score?: number;
              created_at?: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** Delete a provider credential */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/analytics/usage': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Grouped usage/spend for the caller’s organization (reads hourly rollups) */
    get: {
      parameters: {
        query?: {
          group_by?: 'app' | 'route' | 'model' | 'day';
          format?: 'json' | 'csv';
          from?: string;
          to?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              group_by?: string;
              data?: {
                key?: string;
                requests?: number;
                input_tokens?: number;
                output_tokens?: number;
                cost_usd?: number;
              }[];
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/platform/analytics/usage': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Cross-org spend summary grouped by org (platform-admin only) */
    get: {
      parameters: {
        query?: {
          format?: 'json' | 'csv';
          from?: string;
          to?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              group_by?: string;
              data?: {
                key?: string;
                requests?: number;
                input_tokens?: number;
                output_tokens?: number;
                cost_usd?: number;
              }[];
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/audit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List the organization’s audit trail (newest first) */
    get: {
      parameters: {
        query?: {
          limit?: number;
          before?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              data?: {
                object?: string;
                id?: string;
                seq?: number;
                actor?: string;
                action?: string;
                target?: null | string;
                hash?: string;
                created_at?: string;
              }[];
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/routes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List routes with their active-version summary */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              data?: {
                object?: string;
                id?: string;
                model_name?: string;
                cache_enabled?: boolean;
                active_version_id?: null | string;
                active_version?: null | number;
                /** @enum {null|string} */
                active_strategy?: 'priority' | 'weighted' | null;
                version_count?: number;
                target_count?: number;
                created_at?: string;
              }[];
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    put?: never;
    /** Create a route (optionally with an initial active version) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            model_name: string;
            /** @enum {string} */
            strategy?: 'priority' | 'weighted';
            cache_enabled?: boolean;
            targets?: {
              /** Format: uuid */
              credential_id: string;
              provider: string;
              model: string;
              priority?: number;
              weight?: number;
            }[];
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              id?: string;
              model_name?: string;
              cache_enabled?: boolean;
              active_version_id?: null | string;
              created_at?: string;
              versions?: {
                object?: string;
                id?: string;
                version?: number;
                /** @enum {string} */
                strategy?: 'priority' | 'weighted';
                is_active?: boolean;
                created_at?: string;
                targets?: {
                  object?: string;
                  id?: string;
                  credential_id?: string;
                  provider?: string;
                  model?: string;
                  priority?: number;
                  weight?: number;
                  known_model?: boolean;
                }[];
              }[];
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/routes/{routeId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve a route with all versions and targets */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          routeId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              id?: string;
              model_name?: string;
              cache_enabled?: boolean;
              active_version_id?: null | string;
              created_at?: string;
              versions?: {
                object?: string;
                id?: string;
                version?: number;
                /** @enum {string} */
                strategy?: 'priority' | 'weighted';
                is_active?: boolean;
                created_at?: string;
                targets?: {
                  object?: string;
                  id?: string;
                  credential_id?: string;
                  provider?: string;
                  model?: string;
                  priority?: number;
                  weight?: number;
                  known_model?: boolean;
                }[];
              }[];
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** Delete a route and all its versions */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          routeId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/routes/{routeId}/versions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add a new version to a route (not activated automatically) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          routeId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** @enum {string} */
            strategy?: 'priority' | 'weighted';
            targets: {
              /** Format: uuid */
              credential_id: string;
              provider: string;
              model: string;
              priority?: number;
              weight?: number;
            }[];
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              id?: string;
              model_name?: string;
              cache_enabled?: boolean;
              active_version_id?: null | string;
              created_at?: string;
              versions?: {
                object?: string;
                id?: string;
                version?: number;
                /** @enum {string} */
                strategy?: 'priority' | 'weighted';
                is_active?: boolean;
                created_at?: string;
                targets?: {
                  object?: string;
                  id?: string;
                  credential_id?: string;
                  provider?: string;
                  model?: string;
                  priority?: number;
                  weight?: number;
                  known_model?: boolean;
                }[];
              }[];
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/routes/{routeId}/activate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Activate a version (rollback = activate an older one) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          routeId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: uuid */
            version_id: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              id?: string;
              model_name?: string;
              cache_enabled?: boolean;
              active_version_id?: null | string;
              created_at?: string;
              versions?: {
                object?: string;
                id?: string;
                version?: number;
                /** @enum {string} */
                strategy?: 'priority' | 'weighted';
                is_active?: boolean;
                created_at?: string;
                targets?: {
                  object?: string;
                  id?: string;
                  credential_id?: string;
                  provider?: string;
                  model?: string;
                  priority?: number;
                  weight?: number;
                  known_model?: boolean;
                }[];
              }[];
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/routes/{routeId}/cache': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Toggle exact-cache for a route */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          routeId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            cache_enabled: boolean;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              id?: string;
              model_name?: string;
              cache_enabled?: boolean;
              active_version_id?: null | string;
              created_at?: string;
              versions?: {
                object?: string;
                id?: string;
                version?: number;
                /** @enum {string} */
                strategy?: 'priority' | 'weighted';
                is_active?: boolean;
                created_at?: string;
                targets?: {
                  object?: string;
                  id?: string;
                  credential_id?: string;
                  provider?: string;
                  model?: string;
                  priority?: number;
                  weight?: number;
                  known_model?: boolean;
                }[];
              }[];
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    trace?: never;
  };
  '/api/v1/traffic': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List recent requests (most recent first) */
    get: {
      parameters: {
        query?: {
          limit?: number;
          status?: 'ok' | 'error' | 'rate_limited' | 'budget_exceeded';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              data?: {
                object?: string;
                id?: string;
                app_id?: string;
                key_id?: null | string;
                route_id?: null | string;
                request_id?: string;
                provider?: string;
                model?: string;
                input_tokens?: number;
                output_tokens?: number;
                cost_usd?: number;
                /** @enum {string} */
                status?: 'ok' | 'error' | 'rate_limited' | 'budget_exceeded';
                latency_ms?: null | number;
                created_at?: string;
              }[];
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/traffic/stream': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Live request feed (Server-Sent Events)
     * @description text/event-stream of traffic.event objects for the caller’s org.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/traffic/{requestId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Trace detail: all events for a request/trace id */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          requestId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              data?: {
                object?: string;
                id?: string;
                app_id?: string;
                key_id?: null | string;
                route_id?: null | string;
                request_id?: string;
                provider?: string;
                model?: string;
                input_tokens?: number;
                output_tokens?: number;
                cost_usd?: number;
                /** @enum {string} */
                status?: 'ok' | 'error' | 'rate_limited' | 'budget_exceeded';
                latency_ms?: null | number;
                created_at?: string;
              }[];
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/chat/completions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create a chat completion (streaming or non-streaming)
     * @description OpenAI-compatible. Requires a virtual key: `Authorization: Bearer rk_live_…`. With `stream:true` the response is an SSE stream of `chat.completion.chunk` events.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            model: string;
            messages: {
              /** @enum {string} */
              role: 'system' | 'user' | 'assistant';
              content:
                | string
                | {
                    [key: string]: unknown;
                  }[];
            }[];
            stream?: boolean;
            max_tokens?: number;
            temperature?: number;
          };
        };
      };
      responses: {
        /** @description A chat.completion object, or an SSE stream when stream=true. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/models': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List available models */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              object?: string;
              data?: {
                id?: string;
                /** @enum {string} */
                object?: 'model';
                created?: number;
                owned_by?: string;
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/models/{model}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve a model by id */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          model: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              id?: string;
              /** @enum {string} */
              object?: 'model';
              created?: number;
              owned_by?: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: {
                message?: string;
                type?: string;
                code?: string;
                param?: null | string;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
